---
openapi: 3.0.0
info:
  title: Network-Management-Api
  description: API for network and device management
  contact:
    email: achen178@my.bcit.ca
  version: 1.0.0
servers:
- url: /
paths:
  /health:
    get:
      operationId: app.get_health
      responses:
        '200':
          description: ok
  /devices:
    get:
      tags:
        - Device
      description: returns all registered devices
      operationId: app.get_devices
      parameters:
        - in: query
          name: start_timestamp
          description: limit number of records to return
          schema:
            type: string
            format: date-time
            example: 2022-10-04T10:05:02.149417
        - in: query
          name: end_timestamp
          description: limit number of records to return
          schema:
            type: string
            format: date-time
            example: 2022-10-04T10:05:02.149417
      responses:
        '200':
          description: Success! List of all the devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceCreate'
        '400':
          description: failed to retrieve device list.Either not found or invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /networks:
    get:
      tags:
        - Networks
      description: Get a list of networks
      operationId: app.get_networks
      parameters:
        - in: query
          name: start_timestamp
          description: limit number of records to return
          schema:
            type: string
            format: date-time
            example: 2022-10-04T10:05:02.149417
        - in: query
          name: end_timestamp
          description: limit number of records to return
          schema:
            type: string
            format: date-time
            example: 2022-10-04T10:05:02.149417
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NetworkCreate'
        '400':
          description: failed to retrieve network list.Either not found or invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    NetworkCreate:
      required:
      - network_id
      - network_name
      - network
      - subnet_mask
      type: object
      properties:
        network_id:
          type: integer
          format: int64
          example: 1
        network_name:
          type: string
          example: network name
        network:
          type: string
          example: 192.168.0.0
        subnet_mask:
          type: string
          example: 255.255.255.0
        gateway:
          type: string
          example: 192.168.0.1
        dns:
          type: string
          example: 192.168.0.1
        device_count:
          type: integer
          format: int32
          example: 10
    DeviceCreate:
      required:
      - device_id
      - device_name
      - mac
      - ip
      - latency
      - network_id
      type: object
      properties:
        device_id:
          type: integer
          format: int64
          example: 1
        device_name:
          type: string
          example: device name
        mac:
          type: string
          example: 0a:51:4b:76:a0:f8
        ip:
          type: string
          example: 192.168.0.50
        latency:
          type: number
          format: float64
          example: 1.45

        network_id:
          type: integer
          format: int64
          example: 1
        last_update:
          type: string
          format: date-time